services:
  app:
    build:
      context: .
      args:
        - PUBLIC_BASE_URL=${PUBLIC_BASE_URL}
        - PRIVATE_DATABASE_URL=${PRIVATE_DATABASE_URL}
        - PRIVATE_BETTER_AUTH_SECRET=${PRIVATE_BETTER_AUTH_SECRET}
        - PRIVATE_GOOGLE_CLIENT_ID=${PRIVATE_GOOGLE_CLIENT_ID}
        - PRIVATE_GOOGLE_CLIENT_SECRET=${PRIVATE_GOOGLE_CLIENT_SECRET}
        - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - PRIVATE_S3_BUCKET=${PRIVATE_S3_BUCKET}
        - PRIVATE_S3_REGION=${PRIVATE_S3_REGION}
        - PRIVATE_S3_ENDPOINT=${PRIVATE_S3_ENDPOINT}
        - PRIVATE_S3_ACCESS_KEY_ID=${PRIVATE_S3_ACCESS_KEY_ID}
        - PRIVATE_S3_SECRET_ACCESS_KEY=${PRIVATE_S3_SECRET_ACCESS_KEY}
        - PRIVATE_S3_PUBLIC_URL=${PRIVATE_S3_PUBLIC_URL}
    environment:
      - PUBLIC_BASE_URL=${PUBLIC_BASE_URL}
      - PRIVATE_DATABASE_URL=${PRIVATE_DATABASE_URL}
      - PRIVATE_BETTER_AUTH_SECRET=${PRIVATE_BETTER_AUTH_SECRET}
      - PRIVATE_GOOGLE_CLIENT_ID=${PRIVATE_GOOGLE_CLIENT_ID}
      - PRIVATE_GOOGLE_CLIENT_SECRET=${PRIVATE_GOOGLE_CLIENT_SECRET}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PRIVATE_S3_BUCKET=${PRIVATE_S3_BUCKET}
      - PRIVATE_S3_REGION=${PRIVATE_S3_REGION}
      - PRIVATE_S3_ENDPOINT=${PRIVATE_S3_ENDPOINT}
      - PRIVATE_S3_ACCESS_KEY_ID=${PRIVATE_S3_ACCESS_KEY_ID}
      - PRIVATE_S3_SECRET_ACCESS_KEY=${PRIVATE_S3_SECRET_ACCESS_KEY}
      - PRIVATE_S3_PUBLIC_URL=${PRIVATE_S3_PUBLIC_URL}
